baseURL = 'https://fiveminutesread.github.io/'
languageCode = 'en-us'
title = 'Five Minutes Reads'
canonifyurls = true
paginate = 15
author = 'Hatim'
theme = 'newsroom'
[sitemap]
    changeFreq = 'daily'


